name: eros_fe
description: An unofficial e-hentai app

publish_to: 'none'
version: 1.8.0+553

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 国际化
  flutter_localizations:
    sdk: flutter
  # 图标
  cupertino_icons: ^1.0.3

  intl: ^0.19.0
  font_awesome_flutter: ^10.4.0
#  line_icons: ^2.0.1

  # 网络请求
  dio: ^5.1.1

  cookie_jar: ^4.0.2
  dio_cookie_manager: ^3.0.0
  webview_cookie_manager: ^2.0.6
  shared_preferences: ^2.0.5
  oktoast: ^3.0.0
  html_unescape: ^2.0.0
  enum_to_string: ^2.0.1
  flutter_inappwebview: ^6.0.0
  html: ^0.15.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.0.3
  get: ^4.3.8
  photo_view: ^0.15.0
  cached_network_image: ^3.0.0
  extended_image: ^9.0.4
  liquid_progress_indicator_ns: ^1.0.0
  logger: ^2.0.2+1
  waterfall_flow: ^3.0.1
  modal_bottom_sheet: ^3.0.0
  local_auth: ^2.2.0
  flutter_egg:
    git:
      url: https://github.com/honjow/flutter_egg.git
  # 从分享菜单打开
  receive_sharing_intent: ^1.8.0
#    git: https://github.com/Nahrawene-ben-hmida/receive_sharing_intent
  # 分享
  share_plus: ^10.0.2
  # 权限检查
  permission_handler: ^11.0.0
  # 缓存
  flutter_cache_manager: ^3.0.2
  # 图片保存
  image_gallery_saver: '^2.0.3'
#    git: https://github.com/hui-z/image_gallery_saver.git
  # 滑动删除
  flutter_slidable: ^3.0.0
  scrollable_positioned_list: ^0.3.2
  reorderables: ^0.6.0
  basic_utils: ^5.2.2
  # 震动
  flutter_vibrate: #^1.3.0
    git:
      url: https://github.com/nespjin/flutter_vibrate.git
  vibration: ^2.0.0
  # 文件选择
  file_picker: ^8.0.0+1
  # 评星
  flutter_rating_bar: ^4.0.0
  custom_pop_up_menu: ^1.2.0
  flutter_downloader:
    git:
      url: https://github.com/honjow/flutter_downloader.git
      ref: dev
  copy_with_extension: ^5.0.0
  package_info: ^2.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  #translator: ^0.1.7
  google_translator:
    git: https://github.com/aaalkoud/google-translator.git
#  orientation: ^1.3.0
  device_info_plus: ^11.1.0
  flutter_easyrefresh: ^2.2.1
  flutter_markdown: ^0.7.1
  archive: ^3.1.2
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  extended_sliver: ^2.0.0
  blur: ^4.0.0
  sprintf: ^7.0.0
  keframe: ^3.0.0
  executor: ^2.2.2
  synchronized: ^3.0.0
  isolate_handler: ^1.0.0
  worker_manager: ^7.0.2
  collection: ^1.17.0
  zoom_widget: ^2.0.0
  english_words: ^4.0.0
  scroll_to_index: ^3.0.1
  throttling: ^2.0.1
  sleek_circular_slider: ^2.0.1
  linked_scroll_controller: ^0.2.0
  webdav_client: ^1.1.0
#    git:
#      url: https://github.com/honjow/webdav_client.git
  auto_animated: ^3.0.0
#  learning_language:
#    git:
#      url: https://github.com/honjow/learning.git
#      path: packages/learning_language
  encrypt: ^5.0.1
  wakelock_plus: ^1.2.8
  jinja: ^0.6.0
  image: ^4.1.3
  palette_generator: ^0.3.2
  getwidget: ^5.0.0
  open_filex: ^4.1.1
  flustars: ^2.0.1
#  dio_smart_retry: ^7.0.1
  flutter_smart_dialog: ^4.5.4
  system_proxy: ^0.1.0
  easy_animated_tabbar: ^0.0.1
  contained_tab_bar_view: ^0.8.0
  buttons_tabbar: ^1.3.2
  event_bus: ^2.0.0
  open_by_default:
    git:
      url: https://github.com/honjow/open_by_default.git
  flex_color_picker: ^3.0.0
  bitsdojo_window: ^0.1.1
#  image_picker: ^0.8.5
  sliver_tools: ^0.2.6
  flutter_boring_avatars:
    git:
      url: https://github.com/xioxin/flutter_boring_avatars.git
  archive_async:
    git:
      url: https://github.com/xioxin/archive_async.git
#  image_compare: ^1.1.2
  isolate: ^2.1.1
  octo_image: ^2.0.0
#  google_ml_kit: ^0.18.0
  google_mlkit_barcode_scanning: ^0.12.0
#  google_mlkit_translation: ^0.3.0
  google_mlkit_language_id: ^0.11.0
  flutter_custom_license_page: ^0.0.3
  flutter_list_view: ^1.1.18
  preload_page_view: ^0.2.0
  linkfy_text:
    git:
      url: https://github.com/honjow/linkfy_text.git
      ref: url_identifing
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.0-dev.8
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^4.0.0
  flutter_android_volume_keydown: #^1.0.0
#    path: ../flutter_android_volume_keydown
    git:
      url: https://github.com/honjow/flutter_android_volume_keydown.git
      ref: dev
  sentry_flutter: ^8.2.0
  system_network_proxy: #^1.0.2
    git:
      url: https://github.com/honjow/system_network_proxy.git
      path: system_network_proxy
  flutter_socks_proxy: ^0.0.2
  gesture_zoom_box: ^0.0.4
  rotated_corner_decoration: ^2.0.0
  cross_file: ^0.3.3+2
#  image_save: ^5.0.0
  fluentui_system_icons: ^1.1.185
  flutter_keyboard_visibility: ^6.0.0
  extended_nested_scroll_view: ^6.0.0
  shared_storage: ^0.8.0
  mime: ^2.0.0
  saf:
    git:
      url: https://github.com/honjow/saf.git
      ref: master
  flutter_widget_from_html_core: ^0.15.2
  quiver: ^3.2.0 # 工具库
  native_dio_adapter: ^1.0.0+2
  firebase_analytics: ^10.6.3
  firebase_crashlytics: ^3.4.3
  firebase_performance_dio: ^0.7.1
  pull_down_button: ^0.10.1
  dio_cache_interceptor_file_store: ^1.2.2
  flutter_windowmanager: ^0.2.0
  integral_isolates: ^0.5.1
  cupertino_battery_indicator: ^1.1.0
  mysql_client: ^0.0.27
  blurhash_ffi: ^1.2.2
  cached_annotation: ^1.6.0
  chinese_font_library: ^1.2.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter

  # flutter pub run build_runner build --delete-conflicting-outputs
  # flutter pub run build_runner watch --delete-conflicting-outputs

  # flutter pub run intl_utils:generate
  intl_utils: ^2.8.7

  # flutter pub run apn_json2model
#  apn_json2model: ^2.3.0
  # flutter pub run json_to_model
  json_to_model: #^3.2.4
    git:
      url: https://github.com/honjow/json_to_model.git
      ref: dev
#    path: ../json_to_model

  build_runner: ^2.4.6
  json_serializable: ^6.0.1
  json_annotation: ^4.8.1
  copy_with_extension_gen: ^5.0.0
  isar_generator: ^3.0.0
#  flutter_lints: ^5.0.0
  cached: ^1.6.1

dependency_overrides:
  collection: ^1.19.0
#  win32: ^4.0.0
#  js: ^0.7.0
#  intl: ^0.19.0
  meta: ^1.14.0
  mime: ^2.0.0
  intl_utils: ^2.8.7
  analyzer: ^6.0.0

flutter_intl:
  enabled: true
  class_name: L10n

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/templates/epub/META-INF/
    - assets/templates/epub/OEBPS/
    - assets/templates/epub/OEBPS/content/
    - assets/templates/epub/OEBPS/content/resources/
    - assets/images/
