name: fehviewer
description: fehviewer

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.63+463

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 国际化
  flutter_localizations:
    sdk: flutter
  # 图标
  cupertino_icons: ^1.0.3

  intl: ^0.17.0
  font_awesome_flutter: ^10.1.0
#  line_icons: ^2.0.1

  # 网络请求
  dio: ^4.0.6
  dio_http_cache: any

  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  webview_cookie_manager: ^2.0.6
  shared_preferences: ^2.0.5
  oktoast: ^3.0.0
  sqflite: ^2.0.0+3
  html_unescape: ^2.0.0
  enum_to_string: ^2.0.1
  flutter_inappwebview: ^5.3.2
  html: ^0.15.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.3
  tuple: ^2.0.0
  get: ^4.3.8
  get_storage: ^2.0.3
  photo_view: ^0.14.0
  cached_network_image: ^3.0.0
  extended_image: ^6.0.1
  liquid_progress_indicator_ns: ^1.0.0
  logger: ^1.0.0
  waterfall_flow: ^3.0.1
  modal_bottom_sheet: ^2.0.0
  local_auth: ^2.0.2
  flutter_egg:
    git:
      url: https://github.com/honjow/flutter_egg.git
  # 从分享菜单打开
  receive_sharing_intent: ^1.4.5
  # 分享
  share: ^2.0.1
  # 权限检查
  permission_handler: ^10.0.0
  # 缓存
  flutter_cache_manager: ^3.0.2
  # 图片保存
  image_gallery_saver: any
  # 滑动删除
  flutter_slidable: ^1.0.0
  scrollable_positioned_list: ^0.3.2
  reorderables: ^0.5.0
  basic_utils: ^4.0.1
  # 震动
  flutter_vibrate: ^1.3.0
  # 文件选择
  file_picker: ^4.1.2
  # 评星
  flutter_rating_bar: ^4.0.0
  custom_pop_up_menu: ^1.2.0
#  flutter_downloader: ^1.6.0
  flutter_downloader:
    git:
      url: https://github.com/honjow/flutter_downloader.git
      ref: dev
  floor: ^1.1.0
  copy_with_extension: ^4.0.0
  package_info: ^2.0.0

  pretty_dio_logger: ^1.2.0-beta-1
  translator: ^0.1.7
  orientation: ^1.3.0
  vibration: ^1.7.4-nullsafety.0
  moor_flutter: ^4.0.0
  device_info: ^2.0.1
  flutter_easyrefresh: ^2.2.1
  flutter_markdown: ^0.6.2
  archive: ^3.1.2
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  extended_sliver: ^2.0.0
  blur: ^3.0.0
#  extended_text: ^7.0.0
  sprintf: ^6.0.0
  keframe: ^3.0.0
  executor: ^2.2.2
  synchronized: ^3.0.0
  isolate_handler: ^1.0.0
  worker_manager: ^4.2.4
  collection: ^1.15.0
  zoom_widget: ^0.2.1
  english_words: ^4.0.0
  scroll_to_index: ^3.0.1
  throttling: ^1.0.0
  sleek_circular_slider: ^2.0.1
  linked_scroll_controller: ^0.2.0
  persistent_bottom_nav_bar: ^4.0.2
  webdav_client: ^1.1.0
  auto_animated: ^3.0.0
  learning_language:
    git:
      url: https://github.com/honjow/learning.git
      path: packages/learning_language
  encrypt: ^5.0.1
  wakelock: ^0.6.1+1
  jinja: ^0.3.4
  restart_app: ^1.1.0
  image: ^3.0.8
  palette_generator: ^0.3.2
  getwidget: ^3.0.1
  open_file: ^3.2.1
  flustars: ^2.0.1
  dio_smart_retry: ^1.0.3
  flutter_smart_dialog: ^4.5.4
  system_proxy: ^0.1.0
  sqflite_common_ffi: ^2.1.0
  easy_animated_tabbar: ^0.0.1
  contained_tab_bar_view: ^0.8.0
  buttons_tabbar: ^1.3.2
  event_bus: ^2.0.0
  extended_nested_scroll_view: ^5.0.0
#  sentry_flutter: ^6.5.0-beta.1
  open_by_default:
    git:
      url: https://github.com/honjow/open_by_default.git
  flex_color_picker: ^2.3.0
  bitsdojo_window: ^0.1.1+1
  image_picker: ^0.8.5
  sliver_tools: ^0.2.6
  flutter_boring_avatars:
    git:
      url: https://github.com/xioxin/flutter_boring_avatars.git
  archive_async:
    git:
      url: https://github.com/xioxin/archive_async.git
  image_compare: ^1.1.2
  isolate: ^2.1.1
  octo_image: ^1.0.2
  google_mlkit_barcode_scanning: ^0.4.0
#  google_mlkit_translation: ^0.3.0
  # google_mlkit_language_id 在iOS上有问题。会闪退或者应用卡死
#  google_mlkit_language_id: 0.3.0
  flutter_custom_license_page: ^0.0.3
  flutter_list_view: ^1.1.18
  fullscreen: ^1.0.3
  preload_page_view: ^0.1.6
  linkfy_text:
    git:
      url: https://github.com/honjow/linkfy_text.git
      ref: url_identifing

dev_dependencies:
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # flutter packages pub run build_runner watch

  # flutter pub run intl_utils:generate
  intl_utils: ^2.5.1
  # flutter pub run apn_json2model
  apn_json2model: ^2.3.0
  build_runner: ^2.0.3
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0

  floor_generator: ^1.1.0
  copy_with_extension_gen: ^4.0.0

  # git hook 相关
  process_run: ^0.12.1+1
  git_hooks: ^0.1.6

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
  json_serializable: ^6.0.1

flutter_intl:
  enabled: true
  class_name: L10n

flutter:
  uses-material-design: true
#  fonts:
#    - family: AppleEmoji
#      fonts:
#        - asset: fonts/AppleColorEmoji.ttf
#    - family: Seguiemj
#      fonts:
#        - asset: fonts/seguiemj.ttf
#    - family: SourceHanSansSC
#      fonts:
#        - asset: fonts/SourceHanSansSC-Regular.otf
#    - family: OpenMoji
#      fonts:
#        - asset: fonts/OpenMoji-Color.ttf


  assets:
    - assets/
    - assets/templates/epub/META-INF/
    - assets/templates/epub/OEBPS/
    - assets/templates/epub/OEBPS/content/
    - assets/templates/epub/OEBPS/content/resources/
    - assets/images/
