# 自动构建 Apk
name: Build apk

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  push:
    tags:
      - v*apk

# 这个工作流程需要执行的任务
jobs:
  process:
    name: Build process
    runs-on: ubuntu-latest
    # 这个任务的步骤
    steps:
      # 拉取项目代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.ENCODED_GIT_CRYPT }}
      # 建立 java 环境
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      # 建立 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-gradle
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-flutter
          path: /opt/hostedtoolcache/flutter

      - name: Flutter pub get
        run: flutter pub get

      - name: Decode keystore
        run: echo $ENCODED_KEYSTORE | base64 -di > android/app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}

      # 打包 APK
      - name: Collect Apks
        run: flutter build apk --release --split-per-abi
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/*.apk
